#
#  Example configuration file to config @alpa/api project.
#  Created On 30 January 2022
#

auth:
    username: alpa
    email: alpa@example.com
    password: short_lived
database:
    connection: redis://redis:6379
    channels:
        codes: 0
        tokens: 1
server:
    host: 0.0.0.0
    port: 1727
    secret: 3PWSzUzBRA722PdnyFwzVrXbangmFsQkLe98jjaEnDw9o8cW7fcWNkURc92GB5SF
    cors:
        - https://alpa.vercel.app
        - http://localhost:3000
