#
#  Example configuration file to config @alpa/api project.
#  Created On 30 January 2022
#

auth:
    username: alpa
    email: alpa@example.com
    password: short_lived
database:
    host: localhost
    port: 6379
    password: null
    channels:
        codes: 0
        tokens: 1
server:
    host: localhost
    port: 1727
    secret: [CREATE A 64 CHARACTER RANDOM STRING HERE]
