#
#  Example configuration file to config @alpa/api project.
#  Created On 30 January 2022
#

# authentication of alpa's API
auth:
    # username and password used to login to
    # alpa's API
    username: alpa
    password: short_lived

    # (not used currently) will be used to fetch
    # an avatar from Gravatar later
    email: alpa@example.com

# database configuration
database:
    # the database connection URL in the redis:// or rediss:// protocol
    connection: redis://redis:6379

    # different redis databases used for different purposes
    channels:
        # storing short codes
        codes: 0

        # storing authentication token blacklist
        tokens: 1

        # storing additional critical configuration
        config: 2
